### ISSUE TITLE
[Suggestion] Download categories from other users

### ISSUE THREAD

**Issue by juanstakys** [vukani-dev/improvement-roll#4]
And being able to make own categories downloadable.

**Comment by StakysJC** [comment]
Well, better than downloading it would be "sharing" I guess.

**Comment by vukani-dev** [comment]
Hello! Thank you for showing an interest! 
This is definitely the long term goal I had envisioned for the project. I opted to take it out, just to get the initial version deployed.
I'd say something like this would be in the application by the end of the May (based on my free time).


If you have more detailed thoughts about sharing categories feel free to share.

**Comment by simonsan** [comment]
Could be nice to make an `improvement-roll_categories` repository and let users pull request their categories there. Or for more inclusivity for people not able to use github some small single page application to upload/download categories.

**Comment by benne-dee** [comment]
Note that such a feature to be effective would require either :
1. Some sort of curating (like a curated repository @simonsan suggested) 
    which is extra work (but doable) for the maintainer(s).
2. Well designed sorting/searching interface if uploads listing is open to all. 
    Otherwise you would see a lot of spam eventually.

Strengthening the import/export feature (with say versioning and metadata fields like author etc) would be good step in this direction I think.
As people can always upload/download/share those files using their most preferred mediums. 
And for multiple independent community upload/download site(s) you'd need a common transfer format anyway.

I vote for yaml being the standard export/sharing format. Since it's human readable (and easily edited in any text editor). Also it is readily converted to json for processing.

**Comment by vukani-dev** [comment]
I've been working on the backend/repo on the side here https://github.com/vukani-dev/improvement-roll-service.

What I'm initially thinking is doing the curation via pull requests to the category directory in the repo.
Then on merge having a CICD of some sort that will rebuild the project and host it somewhere.

The app will just request to the hosted service for shared categories. With pagination and filtering (based on genre, author, etc) so its more manageable.
That way there will be a rapid update of shared categories without the need to redeploy the application.

I also think this implementation wont trigger an Anti-Feature for F-Droid, But I'm not 100% certain.
Thoughts?

**Comment by simonsan** [comment]
I think a version field in the schema for the categories would make sense though, in addition to the date/time field. Maybe we should discuss that in the `improvement roll service` repository.

**Comment by vukani-dev** [comment]
Hello! I have added this in version 1.3.0. Please check the README and the `improvement-roll-service` repo for more details.
Thank you, and please reach out if there are any issues or other thoughts!
